//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_rol_opcion
    {
        public int id_rol_opcion { get; set; }
        public int id_rol { get; set; }
        public string rol { get; set; }
        public int id_opciones { get; set; }
        public string opcion { get; set; }
    }
}
